# Generated by Django 3.1 on 2020-08-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='auther',
            new_name='author',
        ),
    ]
