# Generated by Django 3.1 on 2020-08-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_auto_20200816_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='usefulll_review',
            new_name='usefull_review',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='usefulll_review_record',
            new_name='usefull_review_record',
        ),
    ]
