# Generated by Django 3.1 on 2020-08-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='postdata',
            new_name='postdate',
        ),
    ]
